# Generated by Django 3.1.4 on 2020-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201108_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='mercury', max_length=50, verbose_name='grade'),
        ),
    ]
