# Generated by Django 3.1.3 on 2020-11-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201108_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Software', max_length=15, verbose_name='Category'),
        ),
    ]
